apiVersion: skaffold/v2beta23
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: marius24/authentication-service
      context: authentication-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src"
            dest: .
