apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: myzone.com
      http:
        paths:
          - path: /api/users/
            pathType: Prefix
            backend:
              service:
                name: authentication-cluster-ip
                port:
                  number: 3000
