apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: myzone.network
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: authentication-cluster-ip
              servicePort: 3000